version: '3'

networks:
  chatservice_net:
    driver: bridge

services:
  chatservice:
    build: .
    container_name: chatservice_app
    ports:
      - "8081:8080"
      - "50052:50051"
    networks:
      - chatservice_net
    environment:
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: chat_test
      WEB_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 50051
      INITIAL_CHAT_MESSAGE: "Seu nome é FC. Você é a inteligência artificial da Full Cycle. Você é da suporte a programadores e arquitetos de software"
      OPENAI_API_KEY: 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
      MODEL: gpt-3.5-turbo
      MODEL_MAX_TOKENS: 4096
      TEMPERATURE: 0.2
      TOP_P: 0.2
      N: 1
      MAX_TOKENS: 300
      AUTH_TOKEN: 123456
      STOP: ${STOP}

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    networks:
      - chatservice_net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_test
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306  