apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-webapp
spec:
  selector:
    matchLabels:
      app: mysql-webapp
  template:
    metadata:
      labels:
        app: mysql-webapp
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.30-debian
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "webchat"
        - name: MYSQL_USER
          value: "webchat"
        - name: MYSQL_PASSWORD
          value: "webchat"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-webapp
spec:
  selector:
    app: mysql-webapp
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: fabricioveronez/gpt-webapp:v1
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          value: mysql://root:root@mysql-webapp:3306/webchat
        - name: NEXTAUTH_URL
          value: http://localhost:30000/api/auth
        - name: NEXTAUTH_SECRET
          value: "123456"
        - name: KEYCLOAK_CLIENT_ID
          value: gpt-webapp
        - name: KEYCLOAK_CLIENT_SECRET
          value: M8IMlr3clrQPR1UWrJmF8ZJQSsPb12rR
        - name: KEYCLOAK_ISSUER
          value: http://keycloak:8080/realms/master
        - name: CHATSERVICE_URL
          value: "chatservice:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
      name: http
