apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-next
spec:
  selector:
    matchLabels:
      app: mysql-next
  template:
    metadata:
      labels:
        app: mysql-next
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.30-debian
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "chat"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-next
spec:
  selector:
    app: mysql-next
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: fabricioveronez/gpt-nextjs
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          value: mysql://root:root@mysql-next:3306/chat
        - name: NEXTAUTH_URL
          value: http://localhost:8082/api/auth
        - name: NEXTAUTH_SECRET
          value: "123456"
        - name: KEYCLOAK_CLIENT_ID
          value: devopspro
        - name: KEYCLOAK_CLIENT_SECRET
          value: EdzyY0JWfxjhgv4MnqxrxvCjRAjI55Qq
        - name: KEYCLOAK_ISSUER
          value: http://keycloak:8080/realms/master
        - name: NEXT_PUBLIC_API_URL
          value: http://localhost:8082/api
        - name: CHATSERVICE_URL
          value: "chatservice:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs
spec:
  selector:
    app: nextjs
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30002
      name: http
