name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "feature/kubernetes" ]
  pull_request:
    branches: [ "feature/kubernetes" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Passo 01
      run: echo "Construir imagem da aplicação"
    - name: Passo 02
      run: echo "Publicar a imagem no Docker Hub"

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
    - uses: actions/checkout@v3
    - name: Passo 01
      run: echo "Deploy da aplicação"

