name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "feature/kubernetes" ]
  pull_request:
    branches: [ "feature/kubernetes" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: fabricioveronez
        password: ${{secrets.DOCKERHUB_PWD}}
    - name: Construção da imagem Docker Front end
      uses: docker/build-push-action@v3.2.0
      with: 
        context: ./nextjs
        file: ./nextjs/Dockerfile
        push: true
        tags: |
          fabricioveronez/gpt-front:${{github.run_number}}
          fabricioveronez/gpt-front:latest
    - name: Construção da imagem Docker ChatService 
      uses: docker/build-push-action@v3.2.0
      with: 
        context: ./chatservice
        file: ./chatservice/Dockerfile
        push: true
        tags: |
          fabricioveronez/gpt-chatservice:${{github.run_number}}
          fabricioveronez/gpt-chatservice:latest
