name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "feature/kubernetes" ]
  pull_request:
    branches: [ "feature/kubernetes" ]

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: fabricioveronez
        password: ${{secrets.DOCKERHUB_PWD}}
    - name: Construção da imagem Docker Front end
      uses: docker/build-push-action@v3.2.0
      with: 
        context: ./webapp
        file: ./webapp/Dockerfile
        push: true
        tags: |
          fabricioveronez/gpt-front:${{github.run_number}}
          fabricioveronez/gpt-front:latest
    - name: Construção da imagem Docker ChatService 
      uses: docker/build-push-action@v3.2.0
      with: 
        context: ./chatservice
        file: ./chatservice/Dockerfile
        push: true
        tags: |
          fabricioveronez/gpt-chatservice:${{github.run_number}}
          fabricioveronez/gpt-chatservice:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
    - uses: actions/checkout@v3

    - name: Configurar as credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update KubeConfig
      shell: bash
      run: |
        aws eks update-kubeconfig --name eks --region us-east-1

    - name: Troca dos parametros 
      shell: bash 
      run: |
        sed -i "s/{{API_TOKEN}}/${{ secrets.OPENAI_API_TOKEN }}/g" ./k8s/deployment-chatservice.yaml
        
    - name: Deploy To Cluster
      shell: bash
      run: kubectl apply -f ./k8s/deployment-chatservice.yaml

    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        manifests: |
          k8s/deployment-chatservice.yaml
          k8s/deployment-nextjs.yaml
        images: |
          fabricioveronez/gpt-chatservice:${{github.run_number}}
          fabricioveronez/gpt-webapp:${{github.run_number}}
